@startuml

actor Client
participant Client

box "Prime"
    participant "client-api"
    participant "payment-processor"
    participant OCS
    participant DAO
end box
participant Stripe

    "client-api" -> "payment-processor" : createPaymentProfile(customer)
    activate "client-api"
    activate "payment-processor"
    note right of "client-api"
        The {customer} object, obtained from OAuth2 authentication
        contains the information required for registering the user
        with a payment service (received from client)
    end note

    alt successful case
        "payment-processor" -> Stripe : POST /v1/customers {customer} (Create new subscriber with Stripe)
        activate Stripe
        "Stripe" -> "payment-processor" : {customerId}
        deactivate Stripe

        "payment-processor" -> "client-api" : {customerId}
        deactivate "payment-processor"

        "client-api" -> DAO : createProfile(name, customerId)
        activate DAO
        DAO -> "client-api" : {result}
        deactivate DAO
        deactivate "client-api"
        note right of "client-api"
            The subscriber has now been registered with {name}
            as the id and {customerId} as the id with Stripe
        end note

    else error
        note right of "payment-processor" : Unroll charge with Stripe etc. (TBD)

    end

@enduml
