@startuml

actor Admin
participant Admin

box "Prime"
    participant "admin-api"
    participant "payment-processor"
    participant Storage
end box
participant Stripe

activate Admin
    "Admin" -> "admin-api" : POST /plans {sku}
    activate "admin-api"
    "admin-api" -> "payment-processor" : POST /plans {sku}

    activate "payment-processor"
    "payment-processor" -> "Storage" : Read product {sku}
    activate "Storage"
    "Storage" -> "payment-processor" : {prod-id}  (e.g. Stripe prod-id)
    deactivate "Storage"

    "payment-processor" -> "Stripe" : POST /v1/plans {prod-id}  (create plan with Stripe)
    activate "Stripe"
    "Stripe" -> "payment-processor" : {plan-id}
    deactivate "Stripe"

    "payment-processor" -> "Storage" : Save plan as a subscription {plan-id}
    activate "Storage"
    "Storage" -> "payment-processor" : {subscription-id}
    deactivate "Storage"

    "payment-processor" -> "admin-api" : {subscription-id}
    deactivate "payment-processor"
    "admin-api" -> "Admin" : {subscription-id}
    deactivate "admin-api"
deactivate Admin

@enduml
