@startuml

participant Client

box "Prime"
    participant "client-api"
    participant "payment-processor"
    participant "storage"
end box
participant Stripe

activate Client
Client -> Client : Collecting payment information
Client -> Stripe : Checkout
activate Stripe
Stripe --> Client: {token}
deactivate Stripe
Client -> "client-api": POST /products {SKU, token}
activate "client-api"
"client-api" -> "payment-processor"
activate "payment-processor"
"payment-processor" -> Stripe: Charge {token}
activate Stripe
Stripe --> "payment-processor": Charge Object {id,result..}
deactivate Stripe
"payment-processor" -> "client-api"
deactivate "payment-processor"
"client-api" --> Client: {result}
deactivate "client-api"
deactivate Client
@enduml
