@startuml

Handset -> Stripe : CC-info
Stripe -> Handset: PaymentToken
Handset --> Prime: Buy(prod, paymentToken, etc.)
Prime -> Stripe: Buy(token, ...)
Stripe --> Prime: Ok
Prime ---> Handset: Response of buy thingy

@enduml
