@startuml

actor Client
participant Client

box "Prime"
    participant "client-api"
    participant "payment-processor"
    participant OCS
    participant DAO
end box
participant Stripe

activate Client
    Client -> Client : Collecting payment information

    Client -> Stripe : Create new source with Stripe
    activate Stripe
    Stripe -> Client : {sourceId}
    deactivate Stripe

    Client -> Client : Select product ({sku})

    Client -> "client-api": POST /products {sku, sourceId, saveCardFlag}
    activate "client-api"

    "client-api" -> "payment-processor" : purchaseProduct(name, sku, sourceId, saveCardFlag)
    activate "payment-processor"

    "payment-processor" -> DAO : getStripeCustomerId(name)
    activate DAO
    DAO -> "payment-processor" : {customerId}
    deactivate DAO

    "payment-processor" -> DAO : getProduct(sku)
    activate DAO
    DAO -> "payment-processor" : {product}
    deactivate DAO

    alt successful case

        "payment-processor" -> Stripe : POST /v1/customers/{customerId}/sources {sourceId}
        activate Stripe
        Stripe -> "payment-processor" : {sourceInfo}
        deactivate Stripe
        note left : Attach new source to customer ({sourceId, customerId})

        "payment-processor" -> Stripe : POST /v1/charges {customerId, sourceId, product.amount, product.currency, product.description}
        activate Stripe
        Stripe -> "payment-processor" : {chargeInfo}
        deactivate Stripe

        alt saveCardFlag is false
            "payment-processor" -> Stripe : DELETE /v1/customer/{customerId}/sources/{sourceId}
             activate Stripe
            Stripe -> "payment-processor" : {result)}
            deactivate Stripe
        end

        "payment-processor" -> DAO: recordChargeInfo(name, chargeInfo)
        activate DAO
        DAO -> "payment-processor" : {result}
        deactivate DAO
        note right
          Charges/refunds to be recorded
          in a "ledger" type of store
        end note

        "payment-processor" -> OCS : updateBucket(name, product.size)
        activate OCS
        OCS -> "payment-processor" : {result}
        deactivate OCS

    else error
         note right of "payment-processor" : Unroll charge with Stripe etc. (TBD)

    end

    "payment-processor" -> "client-api" : {result}
    deactivate "payment-processor"

    "client-api" -> Client : {result}
    deactivate "client-api"

deactivate Client

@enduml
