@startuml

package "Handset" {
  [App]
  [Mobile data]
}


package "Payment service" {
  [Payment]
}

package "Authentication service" {
  [AUTH]
}



package "Host Operator" {
  [PGW]
}

package "GCP - Compute Engine" {
  [OCSGW]
}


package "GCP - Kubernetes" {

  package "Cloud endpoints"{
    [CEP1]
    [CEP2]
  }

  package "PubSub"{
    [CCR]
  }

  database DB

  node "Pod" {
    [ESP1]
    [ESP2]
    [Prime]
  }
}

[App] -- [AUTH]
[Payment] -- [App]
[Payment] -- [Prime]
[Mobile data] -- [PGW] : gtp
[App] - [CEP1] : https
[CEP1] - [ESP1] : http
[CEP2] - [ESP2]: gRPC


[PGW] - [OCSGW]: diameter
[OCSGW] - [CEP2] : gRPC
[ESP1] - [Prime] : http
[ESP2] - [Prime] : gRPC
[Prime] -  DB
[OCSGW] - [CCR] : ccr-topic
[CCR] - [Prime] : ccr-sub

@enduml
