rootProject.name = "ostelco-core"

include(":acceptance-tests")
include(":admin-endpoint")
include(":analytics-grpc-api")
include(":analytics-module")
include(":app-notifier")
include(":appleid-auth-service")
include(":auth-server")
include(":customer-endpoint")
include(":customer-support-endpoint")
include(":data-store")
include(":diameter-ha")
include(":diameter-stack")
include(":diameter-test")
include(":document-data-store")
include(":ekyc")
include(":email-notifier")
include(":ext-auth-provider")
include(":ext-myinfo-emulator")
include(":firebase-extensions")
include(":graphql")
include(":imei-lookup")
include(":jersey")
include(":kts-engine")
include(":logging")
include(":model")
include(":neo4j-admin-tools")
include(":neo4j-store")
include(":ocs-grpc-api")
include(":ocs-ktc")
include(":ocsgw")
include(":payment-processor")
include(":prime")
include(":prime-admin")
include(":prime-modules")
include(":prime-customer-api")
include(":scaninfo-datastore")
include(":scaninfo-shredder")
include(":secure-archive")
include(":slack")
include(":tracing")

include(":sim-administration:es2plus4dropwizard")
include(":sim-administration:jersey-json-schema-validator")
include(":sim-administration:hss-adapter")
include(":sim-administration:ostelco-dropwizard-utils")
include(":sim-administration:simcard-utils")
include(":sim-administration:simmanager")
include(":sim-administration:sm-dp-plus-emulator")

project(":acceptance-tests").projectDir = File("$rootDir/acceptance-tests")
project(":admin-endpoint").projectDir = File("$rootDir/admin-endpoint")
project(":analytics-grpc-api").projectDir = File("$rootDir/analytics-grpc-api")
project(":analytics-module").projectDir = File("$rootDir/analytics-module")
project(":app-notifier").projectDir = File("$rootDir/app-notifier")
project(":appleid-auth-service").projectDir = File("$rootDir/appleid-auth-service")
project(":auth-server").projectDir = File("$rootDir/auth-server")
project(":customer-endpoint").projectDir = File("$rootDir/customer-endpoint")
project(":customer-support-endpoint").projectDir = File("$rootDir/customer-support-endpoint")
project(":data-store").projectDir = File("$rootDir/data-store")
project(":diameter-ha").projectDir = File("$rootDir/diameter-ha")
project(":diameter-stack").projectDir = File("$rootDir/diameter-stack")
project(":diameter-test").projectDir = File("$rootDir/diameter-test")
project(":document-data-store").projectDir = File("$rootDir/document-data-store")
project(":ekyc").projectDir = File("$rootDir/ekyc")
project(":email-notifier").projectDir = File("$rootDir/email-notifier")
project(":ext-auth-provider").projectDir = File("$rootDir/ext-auth-provider")
project(":ext-myinfo-emulator").projectDir = File("$rootDir/ext-myinfo-emulator")
project(":firebase-extensions").projectDir = File("$rootDir/firebase-extensions")
project(":graphql").projectDir = File("$rootDir/graphql")
project(":imei-lookup").projectDir = File("$rootDir/imei-lookup")
project(":jersey").projectDir = File("$rootDir/jersey")
project(":kts-engine").projectDir = File("$rootDir/kts-engine")
project(":logging").projectDir = File("$rootDir/logging")
project(":model").projectDir = File("$rootDir/model")
project(":neo4j-admin-tools").projectDir = File("$rootDir/tools/neo4j-admin-tools")
project(":neo4j-store").projectDir = File("$rootDir/neo4j-store")
project(":ocs-grpc-api").projectDir = File("$rootDir/ocs-grpc-api")
project(":ocs-ktc").projectDir = File("$rootDir/ocs-ktc")
project(":ocsgw").projectDir = File("$rootDir/ocsgw")
project(":payment-processor").projectDir = File("$rootDir/payment-processor")
project(":prime").projectDir = File("$rootDir/prime")
project(":prime-admin").projectDir = File("$rootDir/tools/prime-admin")
project(":prime-modules").projectDir = File("$rootDir/prime-modules")
project(":prime-customer-api").projectDir = File("$rootDir/prime-customer-api")
project(":scaninfo-datastore").projectDir = File("$rootDir/scaninfo-datastore")
project(":scaninfo-shredder").projectDir = File("$rootDir/scaninfo-shredder")
project(":secure-archive").projectDir = File("$rootDir/secure-archive")
project(":slack").projectDir = File("$rootDir/slack")
project(":tracing").projectDir = File("$rootDir/tracing")

project(":sim-administration:es2plus4dropwizard").projectDir = File("$rootDir/sim-administration/es2plus4dropwizard")
project(":sim-administration:jersey-json-schema-validator").projectDir = File("$rootDir/sim-administration/jersey-json-schema-validator")
project(":sim-administration:hss-adapter").projectDir = File("$rootDir/sim-administration/hss-adapter")
project(":sim-administration:ostelco-dropwizard-utils").projectDir = File("$rootDir/sim-administration/ostelco-dropwizard-utils")
project(":sim-administration:simcard-utils").projectDir = File("$rootDir/sim-administration/simcard-utils")
project(":sim-administration:simmanager").projectDir = File("$rootDir/sim-administration/simmanager")
project(":sim-administration:sm-dp-plus-emulator").projectDir = File("$rootDir/sim-administration/sm-dp-plus-emulator")
