package org.ostelco.prime.disruptor

enum class EventMessageType {
    TOPUP_DATA_BUNDLE_BALANCE,
    CREDIT_CONTROL_REQUEST,
    RELEASE_RESERVED_BUCKET,

    UPDATE_BUNDLE,
    ADD_MSISDN_TO_BUNDLE_MAPPING,
    REMOVE_MSISDN_TO_BUNDLE_MAPPING,
}
