# This Dockerfile is used when running locally using docker-compose for Acceptance Testing.

FROM gcr.io/endpoints-release/endpoints-runtime:1

MAINTAINER CSI "csi@telenordigital.com"

COPY pantel-prod.json /esp/
COPY nginx.* /etc/nginx/ssl/
