@startuml

[prime]
note left of prime
    Aggregates modules into a single
    deployable component.
    Components talk with each
    other via disruptor api.
end note

interface "prime-modules" as primeModules
[prime] --> primeModules : <<compile-time>>

note left of primeModules
    Code needed by modules for them
    to be aggregated into prime.
end note

[module(s)] --> primeModules : <<compile-time>>
[module(s)] ..> [module(s)] : <<runtime>>
[prime] ..> [module(s)] : <<runtime>>

@enduml