@startuml

[prime]
note left of prime
    Aggregates modules into a single
    deployable component.
    Components talk with each
    other via disruptor api.
end note

interface "prime-api" as primeApi
[prime] --> primeApi : <<implements>>

interface "ocs-api" as ocsApi
note left of ocsApi: gRPC interface for OCS

[ocs]
note right of ocs
    Online Charging System.
    Implements ocs-api for consumption.
end note

primeApi ..> ocsApi : <<extends>>
note left of primeApi
    Code needed by modules for them
    to be aggregated into prime.
end note

[ocs] ..> primeApi : <<uses>>
[ocs] ..> ocsApi : <<implements>>

@enduml