package org.ostelco.prime.apierror

enum class ApiErrorCode {

    // payment
    // FAILED_TO_CREATE_PAYMENT_PROFILE,
    FAILED_TO_FETCH_PAYMENT_PROFILE,
    FAILED_TO_FETCH_PAYMENT_HISTORY,
    FAILED_TO_GENERATE_STRIPE_EPHEMERAL_KEY,

    // payment source
    FAILED_TO_STORE_PAYMENT_SOURCE,
    FAILED_TO_SET_DEFAULT_PAYMENT_SOURCE,
    FAILED_TO_FETCH_PAYMENT_SOURCES_LIST,
    FAILED_TO_REMOVE_PAYMENT_SOURCE,
    PAYMENT_SOURCE_REJECTED,

    // payment monitor
    FAILED_TO_CHECK_API_VERSION,
    FAILED_TO_CHECK_EVENTS_NOT_DELIVERED,
    FAILED_TO_CHECK_WEBHOOK_ENABLED,
    FAILED_TO_CHECK_WEBHOOK_DISABLED,
    FAILED_TO_FETCH_SUBSCRIBED_TO_EVENTS,
    FAILED_TO_CHECK_SUBSCRIBED_TO_EVENTS,
    FAILED_TO_FETCH_PAYMENT_TRANSACTIONS,
    FAILED_TO_FETCH_PURCHASE_RECORDS,
    FAILED_TO_CHECK_PAYMENT_TRANSACTIONS,

    // notification
    FAILED_TO_STORE_APPLICATION_TOKEN,

    // bundles
    FAILED_TO_FETCH_BUNDLES,

    // products
    FAILED_TO_FETCH_PRODUCT_LIST,
    FAILED_TO_FETCH_PRODUCT_INFORMATION,

    // purchase
    FAILED_TO_PURCHASE_PRODUCT,
    FAILED_TO_REFUND_PURCHASE,

    // referral
    FAILED_TO_FETCH_REFERRALS,
    FAILED_TO_FETCH_REFERRED_BY_LIST,

    // customer
    FAILED_TO_FETCH_CUSTOMER_ID,
    FAILED_TO_FETCH_CUSTOMER,
    FAILED_TO_CREATE_CUSTOMER,
    FAILED_TO_UPDATE_CUSTOMER,
    FAILED_TO_REMOVE_CUSTOMER,

    // audit log
    FAILED_TO_FETCH_AUDIT_LOGS,

    // context
    FAILED_TO_FETCH_CONTEXT,

    // offer
    FAILED_TO_IMPORT_OFFER,

    // plan
    FAILED_TO_FETCH_PLAN,
    FAILED_TO_FETCH_PLANS_FOR_SUBSCRIBER,
    FAILED_TO_STORE_PLAN,
    FAILED_TO_REMOVE_PLAN,
    ALREADY_SUBSCRIBED_TO_PLAN,
    // FAILED_TO_SUBSCRIBE_TO_PLAN,
    // FAILED_TO_RECORD_PLAN_INVOICE,

    // subscription
    FAILED_TO_FETCH_SUBSCRIPTIONS,
    FAILED_TO_CREATE_SUBSCRIPTION,
    FAILED_TO_STORE_SUBSCRIPTION,
    FAILED_TO_REMOVE_SUBSCRIPTION,

    // SIM profile
    FAILED_TO_FETCH_SIM_PROFILES,
    FAILED_TO_PROVISION_SIM_PROFILE,
    FAILED_TO_UPDATE_SIM_PROFILE,
    FAILED_TO_SEND_EMAIL_WITH_ESIM_ACTIVATION_QR_CODE,

    // SIM Admin
    FAILED_TO_FETCH_SIM_PROFILE,
    FAILED_TO_RESERVE_ACTIVATED_SIM_PROFILE,
    FAILED_TO_ACTIVATE_SIM_PROFILE,
    FAILED_TO_ACTIVATE_SIM_PROFILE_WITH_HLR,
    FAILED_TO_DEACTIVATE_SIM_PROFILE_WITH_HLR,
    FAILED_TO_IMPORT_BATCH,

    // Jumio
    FAILED_TO_CREATE_SCANID,
    FAILED_TO_FETCH_SCAN_INFORMATION,
    FAILED_TO_GET_COUNTRY_FOR_SCAN,
    FAILED_TO_CONVERT_SCAN_RESULT,
    FAILED_TO_UPDATE_SCAN_RESULTS,

    FAILED_TO_FETCH_SUBSCRIBER_STATE,
    FAILED_TO_FETCH_REGIONS,

    // eKYC - Singapore
    FAILED_TO_FETCH_CUSTOMER_MYINFO_DATA,
    INVALID_NRIC_FIN_ID,
    FAILED_TO_SAVE_ADDRESS,
}
