FROM alpine:latest

LABEL maintainer="dev@redotter.sg"

RUN apk add --no-cache \
        openssh-client \
        ca-certificates \
        bash

CMD /usr/bin/ssh -oStrictHostKeyChecking=no -R $WEBHOOK_DOMAIN_NAME:443:prime:8080 serveo.net
