package org.ostelco.prime.paymentprocessor.resources

import arrow.core.Try
import com.google.gson.JsonSyntaxException
import com.stripe.exception.SignatureVerificationException
import com.stripe.net.Webhook
import org.ostelco.prime.getLogger
import org.ostelco.prime.jersey.logging.Critical
import org.ostelco.prime.paymentprocessor.publishers.StripeEventPublisher
import javax.validation.Valid
import javax.validation.constraints.NotNull
import javax.ws.rs.HeaderParam
import javax.ws.rs.POST
import javax.ws.rs.Path
import javax.ws.rs.Produces
import javax.ws.rs.core.Response

/**
 * Webhook service for handling Stripe event reports.
 *
 */
@Path("/stripe/event")
class StripeWebhookResource() {

    private val logger by getLogger()

    /* Generated by Stripe and can be obtained from the console. */
    private val endpointSecret = System.getenv("STRIPE_ENDPOINT_SECRET")
            ?: throw Error("Missing environment variable STRIPE_ENDPOINT_SECRET")

    @Critical
    @POST
    @Produces("application/json")
    fun handleEvent(@NotNull @Valid @HeaderParam("Stripe-Signature")
                    signature: String,
                    @NotNull @Valid
                    payload: String): Response =
            Try {
                Webhook.constructEvent(payload, signature, endpointSecret)
            }.fold(
                    ifSuccess = {
                        StripeEventPublisher.publish(it)
                        Response.status(Response.Status.OK)
                                .build()
                    },
                    ifFailure = {
                        when (it) {
                            is JsonSyntaxException -> {
                                logger.error("Invalid payload in Stripe event ${it.message}")
                            }
                            is SignatureVerificationException -> {
                                logger.error("Invalid signature for Stripe event ${it.message}")
                            }
                            else -> {
                                logger.error("Unexpected error for Stripe event ${it.message}")
                            }
                        }
                        Response.status(Response.Status.BAD_REQUEST)
                                .build()
                    }
            )
}
