type: google.api.Service

config_version: 3

name: metrics.new.dev.ostelco.org

title: Prime Metrics Reporter Service gRPC API

apis:
  - name: org.ostelco.prime.metrics.api.OcsgwAnalyticsService

usage:
  rules:
  # All methods can be called without an API Key.
  - selector: "*"
    allow_unregistered_calls: true

authentication:
  providers:
  - id: google_service_account
    issuer: prime-service-account@pantel-2decb.iam.gserviceaccount.com
    jwks_uri: https://www.googleapis.com/robot/v1/metadata/x509/prime-service-account@pantel-2decb.iam.gserviceaccount.com
    audiences: >
      https://metrics.dev.ostelco.org/org.ostelco.prime.metrics.api.OcsgwAnalyticsService,
      metrics.dev.ostelco.org/org.ostelco.prime.metrics.api.OcsgwAnalyticsService,
      metrics.dev.ostelco.org
  rules:
  - selector: "*"
    requirements:
      - provider_id: google_service_account
