package org.ostelco.prime.core

enum class ApiErrorCode(val errorCode: Int) {
    FAILED_TO_CREATE_PAYMENT_PROFILE(0),
    FAILED_TO_FETCH_PAYMENT_PROFILE(1),
    FAILED_TO_STORE_APPLICATION_TOKEN(2),
    FAILED_TO_FETCH_SUBSCRIPTION_STATUS(3),
    FAILED_TO_FETCH_PSEUDONYM_FOR_SUBSCRIBER(4),
    FAILED_TO_FETCH_PAYMENT_HISTORY(5),
    FAILED_TO_FETCH_PRODUCT_LIST(6),
    FAILED_TO_PURCHASE_PRODUCT(7),
    FAILED_TO_FETCH_REFERRALS(8),
    FAILED_TO_FETCH_REFERRED_BY_LIST(9),
    FAILED_TO_FETCH_PRODUCT_INFORMATION(10),
    FAILED_TO_STORE_PAYMENT_SOURCE(11),
    FAILED_TO_SET_DEFAULT_PAYMENT_SOURCE(12),
    FAILED_TO_FETCH_PAYMENT_SOURCES_LIST(13),
    FAILED_TO_UPDATE_PROFILE(14),
    FAILED_TO_FETCH_CONSENT(15)
}