@startuml
package "Docker" {
 [Acceptance Test Runner]
 [Ext-pgw]
 [Ocsgw]
 [ESP]
 [Prime]
 database DB
}

[Acceptance Test Runner] -> [Ext-pgw] : http
[Ext-pgw] -> [Ocsgw] : diameter
[Ocsgw] -> [ESP] : gRPC
[Ocsgw] -> [Prime] : 8082
[ESP] -> [Prime] : 8080
[Prime] ->  DB

@enduml
