logging:
  level: INFO
  loggers:
    org.ostelco: DEBUG
  appenders:
    - type: console
      layout:
        type: json
        customFieldNames:
           level: severity

bqmetrics:
  - type: summary
    name: active_users
    help: Number of active users
    resultColumn: count
    sql: >
        SELECT count(distinct user_pseudo_id) AS count FROM `pantel-2decb.analytics_160712959.events_*`
        WHERE event_name = "first_open"
  - type: gauge
    name: sims_who_have_used_data
    help: Number of SIMs that has used data last 24 hours
    resultColumn: count
    sql: >
        SELECT count(DISTINCT msisdn) AS count FROM `pantel-2decb.data_consumption.raw_consumption`
        WHERE timestamp >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 1 DAY)
  - type: gauge
    name: total_data_used
    help: Total data used last 24 hours
    resultColumn: count
    sql: >
        SELECT sum(bucketBytes) AS count FROM `pantel-2decb.data_consumption.raw_consumption`
        WHERE timestamp >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 1 DAY)
  - type: gauge
    name: revenue_last24hours
    help: Revenue for last 24 hours
    resultColumn: revenue
    sql: >
      SELECT SUM(product.price.amount) as revenue FROM `pantel-2decb.purchases.raw_purchases`
      WHERE TIMESTAMP_MILLIS(timestamp) > TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 24 HOUR)
  - type: gauge
    name: total_paid_users
    help: Number of users who have purchased in last 24 hours
    resultColumn: count
    sql: >
      SELECT COUNT(DISTINCT subscriberId) as count FROM `pantel-2decb.purchases.raw_purchases`
      WHERE TIMESTAMP_MILLIS(timestamp) > TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 24 HOUR)
