apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: bq-metrics-extractor
spec:
  schedule: "*/20 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name:  bq-metrics-extractor
            image: bq-metrics-extractor
          restartPolicy: OnFailure
