apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: bq-metrics-extractor
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name:  bq-metrics-extractor
            image: eu.gcr.io/pantel-2decb/bq-metrics-extractor:latest
            imagePullPolicy: Always
          restartPolicy: Never
