apiVersion: v1
kind: Service
metadata:
  name: prime-service
  labels:
    app: prime
    tier: backend
spec:
  type: LoadBalancer
  loadBalancerIP: 35.195.49.238
  ports:
  - name: grpc
    port: 443
    targetPort: 8443
    protocol: TCP
  selector:
    app: prime
    tier: backend
---
apiVersion: v1
kind: Service
metadata:
  name: prime-api
  labels:
    app: prime
    tier: backend
spec:
  type: LoadBalancer
  loadBalancerIP: 35.233.36.235
  ports:
  - name: https
    port: 443
    protocol: TCP
  selector:
    app: prime
    tier: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prime
  labels:
    app: prime
    tier: backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: prime
        tier: backend
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/prometheus-metrics'
        prometheus.io/port: '8081'
    spec:
      containers:
      - name: esp
        image: gcr.io/endpoints-release/endpoints-runtime:1
        args: [
          "--http2_port=9000",
          "--ssl_port=8443",
          "--status_port=8090",
          "--service=ocs.ostelco.org",
          "--rollout_strategy=managed",
          "--backend=grpc://127.0.0.1:8082"
        ]
        ports:
        - containerPort: 9000
        - containerPort: 8443
        volumeMounts:
        - mountPath: /etc/nginx/ssl
          name: ocs-ostelco-ssl
          readOnly: true
      - name: api-esp
        image: gcr.io/endpoints-release/endpoints-runtime:1
        args: [
          "--http2_port=9002",
          "--ssl_port", "443",
          "--status_port=8092",
          "--service=api.ostelco.org",
          "--rollout_strategy=managed",
          "--backend=127.0.0.1:8080"
        ]
        ports:
        - containerPort: 9002
        - containerPort: 443
        volumeMounts:
        - mountPath: /etc/nginx/ssl
          name: api-ostelco-ssl
          readOnly: true
      - name: prime
        image: eu.gcr.io/pantel-2decb/prime:PRIME_VERSION
        imagePullPolicy: Always
        env:
        - name: FIREBASE_ROOT_PATH
          value: v2
        - name: STRIPE_API_KEY
          valueFrom:
            secretKeyRef:
              name: stripe-secrets
              key: stripeApiKey
        volumeMounts:
        - name: secret-config
          mountPath: "/secret"
          readOnly: true
        ports:
        - containerPort: 8080
        - containerPort: 8081
        - containerPort: 8082
      volumes:
      - name: secret-config
        secret:
          secretName: pantel-prod.json
      - name: api-ostelco-ssl
        secret:
          secretName: api-ostelco-ssl
      - name: ocs-ostelco-ssl
        secret:
          secretName: ocs-ostelco-ssl