package org.ostelco.prime.core

enum class ApiErrorCode {
    FAILED_TO_CREATE_PAYMENT_PROFILE,
    FAILED_TO_FETCH_PAYMENT_PROFILE,
    FAILED_TO_STORE_APPLICATION_TOKEN,
    FAILED_TO_FETCH_SUBSCRIPTION_STATUS,
    FAILED_TO_FETCH_PSEUDONYM_FOR_SUBSCRIBER,
    FAILED_TO_FETCH_PAYMENT_HISTORY,
    FAILED_TO_FETCH_PRODUCT_LIST,
    FAILED_TO_PURCHASE_PRODUCT,
    FAILED_TO_FETCH_REFERRALS,
    FAILED_TO_FETCH_REFERRED_BY_LIST,
    FAILED_TO_FETCH_PRODUCT_INFORMATION,
    FAILED_TO_STORE_PAYMENT_SOURCE,
    FAILED_TO_SET_DEFAULT_PAYMENT_SOURCE,
    FAILED_TO_FETCH_PAYMENT_SOURCES_LIST,
    FAILED_TO_UPDATE_PROFILE,
    FAILED_TO_FETCH_CONSENT,
    FAILED_TO_IMPORT_OFFER,
}