type: google.api.Service

config_version: 3

name: ocs.new.dev.ostelco.org

title: OCS Service gRPC API

apis:
  - name: org.ostelco.ocs.api.OcsService

usage:
  rules:
  # All methods can be called without an API Key.
  - selector: "*"
    allow_unregistered_calls: true

authentication:
  providers:
  - id: google_service_account
    issuer: esp-credentials@pi-ostelco-dev.iam.gserviceaccount.com
    jwks_uri: https://www.googleapis.com/robot/v1/metadata/x509/esp-credentials@pi-ostelco-dev.iam.gserviceaccount.com
    audiences: >
      https://ocs.new.dev.ostelco.org/org.ostelco.ocs.api.OcsService,
      ocs.new.dev.ostelco.org/org.ostelco.ocs.api.OcsService,
      ocs.new.dev.ostelco.org
  rules:
  - selector: "*"
    requirements:
      - provider_id: google_service_account